<?php return array(
'id'=>"oa_bug_all",
'title'=>"Bug列表",
'tablename'=>"oa_bug",
'openurl'=>"Oa/Bug/viewBug",
'editurl'=>"Oa/Bug/addBug",
'addurl'=>"Oa/Bug/addBug",
'orderby'=>"id desc",
'open_window_style'=>"popup:middle",
'actions'=>"add,search,search2,filter,export,page",
'cols'=>"2",
'editcondition'=>"SYS_ADDUSER==loginuser() || loginuser()=='admin'",
'fields'=>array(
 array('id'=>"id",'name'=>"ID",'fieldtype'=>"int",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"project_id",'name'=>"所属项目",'type'=>"dropdown",'data'=>"sql:select id,name from oa_project",'forsearch'=>"true",),
 array('id'=>"subject",'name'=>"标题",'fieldtype'=>"string",'isvisible'=>"true",'visibleWhenAdd'=>"true",'forsearch'=>"true",'nullable'=>"false",),
 array('id'=>"image1",'name'=>"图片",'fieldtype'=>"string",'type'=>"image",'isvisible'=>"true",),
 array('id'=>"content",'name'=>"详情",'fieldtype'=>"string",'type'=>"textarea",'forsearch'=>"true",'nullable'=>"false",'width'=>"240px",'height'=>"100px",),
 array('id'=>"priority",'name'=>"优先级",'fieldtype'=>"string",'type'=>"radio",'data'=>"1:低,2:中,3:高",'defaultdata'=>"中",'forsearch'=>"true",),
 array('id'=>"serious",'name'=>"重要性",'fieldtype'=>"string",'type'=>"radio",'data'=>"1:低,2:中,3:高",'defaultdata'=>"中",'forsearch'=>"true",),
 array('id'=>"status",'name'=>"状态",'fieldtype'=>"string",'type'=>"dropdown",'data'=>"1:未解决,2:已解决,3:不解决,3.1:不算问题,3.2:无法重现,4:暂缓解决,5:需求要求,6:解决中,7:关闭(已验证解决)",'forsearch'=>"true",'nullable'=>"false",),
 array('id'=>"browser",'name'=>"浏览器",'type'=>"checkboxlist",'data'=>"1:Chrome,2:Firefox,3:IE8,4:IE9",),
 array('id'=>"sort",'name'=>"类别",'fieldtype'=>"int",'type'=>"dropdown",'data'=>"1:bug,2:改进,3:新功能",'forsearch'=>"true",'nullable'=>"false",),
 array('id'=>"solveperson",'name'=>"bug解决者",'fieldtype'=>"string",'type'=>"dropdown",'data'=>"sql:select a.name,  b.name as staffusername   from sys_user a left join sys_staff b on   b.username=a.name where a.orgids like   '%orgid()%' order by staffusername",),
 array('id'=>"assign_to",'name'=>"指派给",'fieldtype'=>"string",'type'=>"dropdown",'data'=>"sql:select a.name,  b.name as staffusername   from sys_user a left join sys_staff b on   b.username=a.name where a.orgids like   '%orgid()%' order by staffusername",'forsearch'=>"true",'nullable'=>"false",),
 array('id'=>"hours",'name'=>"工时",'fieldtype'=>"real",'isvisible'=>"false",),
 array('id'=>"begindate",'name'=>"计划开始日期",'fieldtype'=>"date",'type'=>"date",'defaultdata'=>"today()",'isvisible'=>"false",'forsearch'=>"true",),
 array('id'=>"dealline",'name'=>"计划完成日期",'fieldtype'=>"date",'type'=>"date",'defaultdata'=>"today()",'isvisible'=>"false",'forsearch'=>"true",),
 array('id'=>"SYS_ORGID",'name'=>"组织ID",'fieldtype'=>"int",'type'=>"SYS_ORGID",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"SYS_ADDUSER",'name'=>"创建者",'fieldtype'=>"string",'type'=>"SYS_ADDUSER",'readonly'=>"true",'forsearch'=>"true",),
 array('id'=>"SYS_ADDTIME",'name'=>"创建时间",'fieldtype'=>"datetime",'type'=>"SYS_ADDTIME",'readonly'=>"true",'forsearch'=>"true",),
 array('id'=>"SYS_EDITUSER",'name'=>"更新者",'fieldtype'=>"string",'type'=>"SYS_EDITUSER",'readonly'=>"true",),
 array('id'=>"SYS_EDITTIME",'name'=>"更新时间",'fieldtype'=>"datetime",'type'=>"SYS_EDITTIME",'readonly'=>"true",),
 array('id'=>"notes",'name'=>"备注",'fieldtype'=>"string",'type'=>"textarea",'forsearch'=>"true",'width'=>"240px",),
),

) ?>