<?php return array(
'id'=>"oa_project_my_list",
'title'=>"我的项目列表",
'base'=>"oa_project",
'openurl'=>"oa/Project/projectdetail/param:modelid/oa_project_addcopy/detailproject_modelid/oa_project/taskmodelid/oa_project_task/staffmodelid/oa_project_staff/pagetype/open",
'editurl'=>"Oa/Project/editProject/modelid/oa_project_add/pagetype/edit",
'addurl'=>"Oa/Project/editProject/modelid/oa_project_add/pagetype/add",
'filter'=>"SYS_ADDUSER= loginuser() and SYS_ORGID = orgid() and (status='plan' or status='doing') and executerid=loginuser()",
'open_window_style'=>"popup:large",
'pagerows'=>"10",
'cols'=>"2",
'fields'=>array(
 array('id'=>"id",'name'=>"ID",'fieldtype'=>"int",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"code",'name'=>"项目编号",'defaultdata'=>"PROJECT-{yyyy}{mm}{dd}-{newid(project,5)}",'isvisible'=>"false",'readonly'=>"true",'unique'=>"true",'forsearch'=>"true",'nullable'=>"false",),
 array('id'=>"name",'name'=>"项目名称",'unique'=>"true",'forsearch'=>"true",'nullable'=>"false",),
 array('id'=>"order_no",'name'=>"订单号",'fieldtype'=>"string",'type'=>"popupselectone",'data'=>"model:biz_order_list(no:order_no,custid:custid)",'isvisible'=>"false",),
 array('id'=>"custid",'name'=>"客户名称",'type'=>"dropdown",'data'=>"sql:select id,name from biz_customer where SYS_ORGID = orgid()",'isvisible'=>"false",),
 array('id'=>"content",'name'=>"项目概述",'fieldtype'=>"string",'type'=>"textarea",'isvisible'=>"false",),
 array('id'=>"executerid",'name'=>"项目经理",'fieldtype'=>"string",'type'=>"dropdown",'data'=>"sql:select id,name from sys_staff where SYS_ORGID=orgid() order by name",'isvisible'=>"false",),
 array('id'=>"begindate",'name'=>"开始日期",'fieldtype'=>"date",'type'=>"date",'isvisible'=>"false",'forsearch'=>"true",),
 array('id'=>"enddate",'name'=>"结束日期",'fieldtype'=>"date",'type'=>"date",'forsearch'=>"true",),
 array('id'=>"status",'name'=>"状态",'fieldtype'=>"string",'length'=>"10",'type'=>"dropdown",'data'=>",plan:计划,doing:执行,done:完成,cancel:取消",'forsearch'=>"true",),
 array('id'=>"tasktypes",'name'=>"任务分类设置",'type'=>"popupselectone",'data'=>"model:oa_tasktype",'isvisible'=>"false",),
 array('id'=>"finishper",'name'=>"完成率",'fieldtype'=>"float",'type'=>"dropdown",'data'=>"0:0%,0.1:10%,0.2:20%,0.3:30%,0.4:40%,0.5:50%,0.6:60%,0.7:70%,0.8:80%,0.85:85%,0.9:90%,0.95:95%,1:100%",),
 array('id'=>"attach",'name'=>"附件",'fieldtype'=>"string",'type'=>"file",'isvisible'=>"false",),
 array('id'=>"notes",'name'=>"备注",'type'=>"textarea",'isvisible'=>"false",'forsearch'=>"true",),
 array('id'=>"SYS_ADDUSER",'name'=>"创建者",'fieldtype'=>"string",'length'=>"50",'type'=>"SYS_ADDUSER",'isvisible'=>"false",'visibleWhenAdd'=>"false",'readonly'=>"true",'forsearch'=>"true",),
 array('id'=>"SYS_ADDTIME",'name'=>"创建日期",'fieldtype'=>"date",'type'=>"date",'defaultdata'=>"today()",'isvisible'=>"false",'visibleWhenAdd'=>"false",'readonly'=>"true",'forsearch'=>"true",'style'=>"text-align:center",),
 array('id'=>"SYS_EDITUSER",'name'=>"更新人",'fieldtype'=>"string",'length'=>"50",'type'=>"SYS_EDITUSER",'isvisible'=>"false",'visibleWhenAdd'=>"false",'readonly'=>"true",),
 array('id'=>"SYS_EDITTIME",'name'=>"更新时间",'fieldtype'=>"datetime",'type'=>"SYS_EDITTIME",'isvisible'=>"false",'visibleWhenAdd'=>"false",'readonly'=>"true",),
 array('id'=>"SYS_ORGID",'name'=>"组织ID",'fieldtype'=>"int",'type'=>"SYS_ORGID",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
),

) ?>