<?php return array(
'id'=>"oa_project_add",
'title'=>"新增项目",
'base'=>"oa_project",
'wayofcopyfields'=>"onlycopyprop",
'cols'=>"2",
'fields'=>array(
 array('id'=>"id",'name'=>"ID",),
 array('id'=>"code",'name'=>"项目编号",),
 array('id'=>"name",'name'=>"项目名称",),
 array('id'=>"order_no",'name'=>"订单号",),
 array('id'=>"custid",'name'=>"客户名称",),
 array('id'=>"content",'name'=>"项目概述",),
 array('id'=>"executerid",'name'=>"项目经理",),
 array('id'=>"begindate",'name'=>"开始日期",),
 array('id'=>"enddate",'name'=>"结束日期",),
 array('id'=>"status",'name'=>"状态",),
 array('id'=>"tasktypes",'name'=>"任务分类",),
 array('id'=>"finishper",'name'=>"完成率",),
 array('id'=>"attach",'name'=>"附件",),
 array('id'=>"SYS_ADDUSER",'name'=>"创建者",),
 array('id'=>"SYS_ADDTIME",'name'=>"创建日期",),
 array('id'=>"SYS_EDITUSER",'name'=>"更新人",),
 array('id'=>"SYS_EDITTIME",'name'=>"更新时间",),
 array('id'=>"SYS_ORGID",'name'=>"组织ID",),
),

) ?>