<?php return array(
'id'=>"oa_task",
'title'=>"工作列表",
'notes'=>"这个模型很重要，很多没模型继承她，不要随意修改",
'tablename'=>"oa_task",
'filter'=>"SYS_ORGID = orgid()",
'actions'=>"add,del,open,edit,search,search2,page,groupby,view",
'calendar_title_field'=>"name",
'calendar_date_field'=>"begindate",
'fields'=>array(
 array('id'=>"id",'name'=>"ID",'fieldtype'=>"int",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"projectid",'name'=>"项目",'fieldtype'=>"string",'type'=>"dropdown",'data'=>"sql:select id,name from oa_project",),
 array('id'=>"name",'name'=>"任务名称",'fieldtype'=>"string",'type'=>"textarea",'forsearch'=>"true",'nullable'=>"false",),
 array('id'=>"tasktype",'name'=>"工作类别",'fieldtype'=>"string",'type'=>"dropdown",'forsearch'=>"true",),
 array('id'=>"begindate",'name'=>"开始日期",'fieldtype'=>"date",'type'=>"date",'defaultdata'=>"today()",'forsearch'=>"true",),
 array('id'=>"enddate",'name'=>"结束日期",'fieldtype'=>"date",'type'=>"date",'defaultdata'=>"today()",),
 array('id'=>"detail",'name'=>"任务描述",'fieldtype'=>"string",'type'=>"textarea",'isvisible'=>"false",),
 array('id'=>"executerid",'name'=>"执行人",'fieldtype'=>"string",'type'=>"dropdown",'data'=>"sql:select id,name from sys_staff",'defaultdata'=>"Me()",),
 array('id'=>"status",'name'=>"状态",'fieldtype'=>"string",'type'=>"dropdown",'data'=>"plan:计划,doing:执行,done:完成,better:优化,checked:验收,cancel:取消",),
 array('id'=>"finishper",'name'=>"完成率",'type'=>"dropdown",'data'=>"0:0%,0.10:10%,0.20:20%,0.30:30%,0.40:40%,0.50:50%,0.60:60%,0.70:70%,0.80:80%,0.85:85%,0.90:90%,0.95:95%,1:100%",),
 array('id'=>"price",'name'=>"单价",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"totalprice",'name'=>"总价",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"notes",'name'=>"备注",'fieldtype'=>"string",),
 array('id'=>"custid",'name'=>"相关客户ID",'fieldtype'=>"int",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"SYS_ORGID",'name'=>"组织ID",'fieldtype'=>"int",'type'=>"SYS_ORGID",'isvisible'=>"false",'visibleWhenAdd'=>"false",'readonly'=>"true",),
 array('id'=>"SYS_ADDUSER",'name'=>"创建者",'visibleWhenAdd'=>"false",),
 array('id'=>"cat",'name'=>"报告类别",'fieldtype'=>"string",'type'=>"dropdown",'data'=>",日报,周报,月报",),
),

) ?>