<?php return array(
'id'=>"oa_task_add_day",
'title'=>"工作列表",
'tablename'=>"oa_task",
'editurl'=>"oa_task_add_day1",
'filter'=>"tag=2 and SYS_ORGID=orgid()",
'orderby'=>"priority",
'pagerows'=>"5",
'actions'=>"add,open,edit",
'wayofcopyfields'=>"onlycopyprop",
'fields'=>array(
 array('id'=>"id",'name'=>"ID",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"cat",'name'=>"工作类别",'length'=>"50",'defaultdata'=>"日报",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"name",'name'=>"主题",'type'=>"textarea",'nullable'=>"false",'style'=>"width:50%",),
 array('id'=>"priority",'name'=>"重要性",'type'=>"radio",'data'=>"1:紧急,2:一般",'defaultdata'=>"2",'style'=>"width:14%",),
 array('id'=>"begindate",'name'=>"日期",'type'=>"date",'isvisible'=>"false",'nullable'=>"false",),
 array('id'=>"enddate",'name'=>"结束日期",'type'=>"date",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"finishper",'name'=>"完成状态",'type'=>"radio",'data'=>"0:未完成,1:已完成,2:己取消",'defaultdata'=>"0",'visibleWhenAdd'=>"false",'style'=>"width:14%",),
 array('id'=>"executerid",'name'=>"执行人",'type'=>"smartselect",'data'=>"sql:select id,name from sys_staff where SYS_ORGID=orgid() ",'defaultdata'=>"Me()",'isvisible'=>"false",'visibleWhenAdd'=>"true",),
 array('id'=>"notes",'name'=>"备注",'fieldtype'=>"string",'type'=>"textarea",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"tag",'name'=>"标签",'type'=>"dropdown",'data'=>"1:计划概述,2:工作条目,3:总结",'defaultdata'=>"2",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"worktime",'name'=>"工时",'type'=>"radio",'data'=>"1:1,2:2,3:3,4:4,5:5,6:6,7:7,8:8",'defaultdata'=>"3",'style'=>"width:12%",),
 array('id'=>"SYS_ADDUSER",'name'=>"创建者",'type'=>"SYS_ADDUSER",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"SYS_ADDTIME",'name'=>"创建时间",'fieldtype'=>"datetime",'type'=>"SYS_ADDTIME",'isvisible'=>"false",'visibleWhenAdd'=>"false",'readonly'=>"true",'forsearch'=>"true",),
 array('id'=>"SYS_EDITUSER",'name'=>"更新人",'fieldtype'=>"string",'type'=>"SYS_EDITUSER",'isvisible'=>"false",'visibleWhenAdd'=>"false",'readonly'=>"true",),
 array('id'=>"SYS_EDITTIME",'name'=>"更新时间",'fieldtype'=>"datetime",'type'=>"SYS_EDITTIME",'isvisible'=>"false",'visibleWhenAdd'=>"false",'readonly'=>"true",),
 array('id'=>"SYS_ORGID",'name'=>"组织id",'defaultdata'=>"orgid()",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
),

) ?>