<?php return array(
'id'=>"singleneworder",
'title'=>"订单",
'tablename'=>"crm_order",
'openurl'=>"CRM/Order/neworder",
'pagerows'=>"10",
'actions'=>"edit",
'cols'=>"2",
'fields'=>array(
 array('id'=>"id",'name'=>"id",'isvisible'=>"true",'visibleWhenAdd'=>"false",'readonly'=>"true",'width'=>"200px",),
 array('id'=>"no",'name'=>"订单号",'readonly'=>"true",'forsearch'=>"true",'nullable'=>"false",'width'=>"250px",),
 array('id'=>"owner",'name'=>"登录人",'defaultdata'=>"loginuser()",'isvisible'=>"true",'visibleWhenAdd'=>"false",'forsearch'=>"true",'width'=>"200px",),
 array('id'=>"agent",'name'=>"代理商",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"products",'name'=>"产品",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"srctype",'name'=>"来源类型",'type'=>"radio",'data'=>"渠道,直销",'defaultdata'=>"渠道",'readonly'=>"true",'forsearch'=>"true",'width'=>"200px",),
 array('id'=>"custid",'name'=>"用户号",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"customer",'name'=>"客户名称",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"orderdate",'name'=>"订单日期",'type'=>"date",'defaultdata'=>"today()",'forsearch'=>"true",'nullable'=>"false",'width'=>"200px",),
 array('id'=>"amt",'name'=>"数量",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"factmoney",'name'=>"实际金额",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"notes",'name'=>"备注",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"type",'name'=>"订单类型",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"price_part1",'name'=>"软件款",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"price_part2",'name'=>"升级费",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"netcount",'name'=>"节点数",'isvisible'=>"false",'visibleWhenAdd'=>"false",'forsearch'=>"true",),
 array('id'=>"addedmodules",'name'=>"额外模块",'isvisible'=>"false",'visibleWhenAdd'=>"false",'forsearch'=>"true",),
 array('id'=>"status",'name'=>"订单状态",'type'=>"radio",'data'=>"待审批,已确认",'defaultdata'=>"已确认",'readonly'=>"true",'forsearch'=>"true",'width'=>"200px",),
 array('id'=>"danjizhejia",'name'=>"单机折价",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"shengjiedianfei",'name'=>"升节点价格",'fieldtype'=>"string",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"duoshenggao",'name'=>"多升高价格",'fieldtype'=>"real",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"gotmoney",'name'=>"订单金额",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
),

) ?>