<?php return array(
'id'=>"stat_test",
'title'=>"stat_code",
'tablename'=>"crm_order",
'sql'=>"select * from crm_order",
'fields'=>array(
 array('id'=>"id",'name'=>"字段1",'fieldtype'=>"int",),
 array('id'=>"no",'name'=>"字段2",'fieldtype'=>"string",),
 array('id'=>"orderdate",'name'=>"字段3",'fieldtype'=>"date",'type'=>"date",),
 array('id'=>"customer",'name'=>"字段4",'fieldtype'=>"string",),
 array('id'=>"custid",'name'=>"字段5",'fieldtype'=>"string",),
 array('id'=>"products",'name'=>"字段6",'fieldtype'=>"string",),
 array('id'=>"amt",'name'=>"字段7",'fieldtype'=>"int",),
 array('id'=>"gotmoney",'name'=>"字段8",'fieldtype'=>"int",),
 array('id'=>"factmoney",'name'=>"成交价",'fieldtype'=>"int",),
 array('id'=>"fapiao",'name'=>"字段10",'fieldtype'=>"int",),
 array('id'=>"notes",'name'=>"字段11",'fieldtype'=>"string",),
 array('id'=>"agent",'name'=>"字段12",'fieldtype'=>"string",),
 array('id'=>"srctype",'name'=>"订单来源类型",'fieldtype'=>"string",),
 array('id'=>"salesperson",'name'=>"字段14",'fieldtype'=>"string",),
 array('id'=>"attach",'name'=>"字段15",'fieldtype'=>"string",),
 array('id'=>"adduser",'name'=>"字段16",'fieldtype'=>"string",),
 array('id'=>"addtime",'name'=>"字段17",),
 array('id'=>"edittime",'name'=>"字段18",'fieldtype'=>"datetime",'type'=>"datetime",),
 array('id'=>"edituser",'name'=>"字段19",'fieldtype'=>"string",),
 array('id'=>"orgid",'name'=>"字段20",'fieldtype'=>"int",),
 array('id'=>"whogotmoney",'name'=>"字段21",'fieldtype'=>"string",),
 array('id'=>"owner",'name'=>"字段22",'fieldtype'=>"string",),
 array('id'=>"status",'name'=>"状态",'fieldtype'=>"string",),
 array('id'=>"upload",'name'=>"字段24",'fieldtype'=>"string",),
 array('id'=>"danjizhejia",'name'=>"单机折价",'fieldtype'=>"real",),
 array('id'=>"shengbanfei",'name'=>"升版费",'fieldtype'=>"real",),
 array('id'=>"shengjiedianfei",'name'=>"升节点费",'fieldtype'=>"real",),
 array('id'=>"type",'name'=>"字段28",'fieldtype'=>"string",),
)
) ?>