<?php return array(
'id'=>"oa_bug",
'title'=>"Bug列表",
'tablename'=>"oa_bug",
'openurl'=>"oa/Bug/viewbug",
'editurl'=>"Oa/Bug/saveBug/model/oa_bug",
'addurl'=>"Oa/Bug/addBug",
'orderby'=>"SYS_EDITTIME desc",
'open_window_style'=>"popup:middle",
'actions'=>"add,edit,search,search2,filter,import,export,page",
'cols'=>"2",
'editcondition'=>"SYS_ADDUSER==loginuser() || loginuser()=='admin'",
'calendar_title_field'=>"subject",
'calendar_date_field'=>"SYS_ADDTIME",
'fields'=>array(
 array('id'=>"id",'name'=>"ID",'fieldtype'=>"int",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"project_id",'name'=>"所属项目",'type'=>"smartselect",'data'=>"sql:select id,name from oa_project",'forsearch'=>"true",'nullable'=>"false",),
 array('id'=>"subject",'name'=>"标题",'fieldtype'=>"string",'isvisible'=>"true",'visibleWhenAdd'=>"true",'forsearch'=>"true",'nullable'=>"false",),
 array('id'=>"image1",'name'=>"图片",'fieldtype'=>"string",'type'=>"image",'isvisible'=>"true",),
 array('id'=>"content",'name'=>"详情",'fieldtype'=>"string",'type'=>"textarea",'isvisible'=>"false",'forsearch'=>"true",'nullable'=>"false",'height'=>"100px",),
 array('id'=>"priority",'name'=>"优先级",'fieldtype'=>"string",'type'=>"radio",'data'=>"1:低,2:中,3:高",'defaultdata'=>"中",'forsearch'=>"true",),
 array('id'=>"serious",'name'=>"重要性",'fieldtype'=>"string",'type'=>"radio",'data'=>"1:低,2:中,3:高",'defaultdata'=>"低",'forsearch'=>"true",),
 array('id'=>"status",'name'=>"状态",'fieldtype'=>"string",'type'=>"dropdown",'data'=>"1:未解决,2:已解决,3:不解决,3.1:不算问题,3.2:无法重现,4:以后解决,5:需求要求,5.1:设计要求,6:解决中,7:关闭(已验证解决),7.1:暂时关闭",),
 array('id'=>"browser",'name'=>"浏览器",'type'=>"checkboxlist",'data'=>"1:Chrome,2:Firefox,3:IE8,4:IE9",),
 array('id'=>"sort",'name'=>"类别",'fieldtype'=>"int",'type'=>"dropdown",'data'=>"1:bug,2:改进,3:新功能",'isvisible'=>"false",'forsearch'=>"true",'nullable'=>"false",),
 array('id'=>"solveperson",'name'=>"bug解决者",'fieldtype'=>"string",'type'=>"dropdown",'data'=>"sql:select (select name from sys_user where name=a.username limit 0,1) as username,a.name as staffusername from sys_staff a where a.SYS_ORGID=orgid() order by staffusername",'isvisible'=>"false",'visibleWhenAdd'=>"true",),
 array('id'=>"assign_to",'name'=>"指派给",'fieldtype'=>"string",'type'=>"dropdown",'data'=>"sql:select id,name from sys_staff where  (statue=1 or statue='') and  SYS_ORGID=orgid()",'forsearch'=>"true",'nullable'=>"false",),
 array('id'=>"hours",'name'=>"工时",'fieldtype'=>"real",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"begindate",'name'=>"计划开始日期",'fieldtype'=>"date",'type'=>"date",'isvisible'=>"false",'visibleWhenAdd'=>"false",'forsearch'=>"true",),
 array('id'=>"dealline",'name'=>"计划完成日期",'fieldtype'=>"date",'type'=>"date",'isvisible'=>"false",'visibleWhenAdd'=>"false",'forsearch'=>"true",),
 array('id'=>"SYS_ORGID",'name'=>"组织ID",'fieldtype'=>"int",'type'=>"SYS_ORGID",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"SYS_ADDUSER",'name'=>"创建者",'fieldtype'=>"string",'type'=>"SYS_ADDUSER",'isvisible'=>"true",'visibleWhenAdd'=>"false",'readonly'=>"true",'forsearch'=>"true",),
 array('id'=>"SYS_ADDTIME",'name'=>"创建时间",'fieldtype'=>"datetime",'type'=>"SYS_ADDTIME",'isvisible'=>"true",'visibleWhenAdd'=>"false",'readonly'=>"true",'forsearch'=>"true",),
 array('id'=>"SYS_EDITUSER",'name'=>"更新人",'fieldtype'=>"string",'type'=>"SYS_EDITUSER",'isvisible'=>"true",'visibleWhenAdd'=>"false",),
 array('id'=>"SYS_EDITTIME",'name'=>"更新时间",'fieldtype'=>"datetime",'type'=>"SYS_EDITTIME",'visibleWhenAdd'=>"false",'readonly'=>"true",),
 array('id'=>"reply_content",'name'=>"回复内容",'fieldtype'=>"string",'type'=>"textarea",'isvisible'=>"true",'visibleWhenAdd'=>"false",'width'=>"240px",),
),
'children'=>array(
 array('modelid'=>"oa_bug_reply",'name'=>"回复表",'parent_field'=>"id",),
)
) ?>