<?php return array(
'id'=>"oa_bug_customer",
'title'=>"客户问题列表",
'tablename'=>"oa_bug",
'filter'=>"project_id in (select id from oa_project where custid=loginuser_customer_id()) and  is_public=1",
'orderby'=>"SYS_EDITTIME desc ",
'open_window_style'=>"popup:middle",
'actions'=>"add,search,page",
'fields'=>array(
 array('id'=>"id",'name'=>"ID",'fieldtype'=>"int",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"subject",'name'=>"名称",'fieldtype'=>"string",'forsearch'=>"true",'nullable'=>"false",),
 array('id'=>"project_id",'name'=>"所属项目",'fieldtype'=>"int",'type'=>"dropdown",'data'=>"sql:select id,name from oa_project where custid = loginuser_customer_id()",'forsearch'=>"true",'nullable'=>"false",),
 array('id'=>"is_public",'name'=>"是否公开",'type'=>"radio",'data'=>"0:保密,1:公开",'defaultdata'=>"1",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"image1",'name'=>"截图",'fieldtype'=>"string",'type'=>"image",),
 array('id'=>"content",'name'=>"详情",'fieldtype'=>"string",'type'=>"textarea",'isvisible'=>"false",'forsearch'=>"true",'nullable'=>"false",'height'=>"100px",),
 array('id'=>"priority",'name'=>"优先级",'fieldtype'=>"string",'type'=>"radio",'data'=>"1:低,2:中,3:高",'defaultdata'=>"1",'forsearch'=>"true",),
 array('id'=>"serious",'name'=>"重要性",'fieldtype'=>"string",'type'=>"radio",'data'=>"1:低,2:中,3:高",'defaultdata'=>"1",'forsearch'=>"true",),
 array('id'=>"browser",'name'=>"浏览器",'fieldtype'=>"string",'type'=>"checkboxlist",'data'=>"1:Chrome,2:Firefox,3:IE8,4:IE9",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"status",'name'=>"状态",'fieldtype'=>"string",'type'=>"dropdown",'data'=>"1:未解决,2:已解决,3:不解决,3.1:不算问题,3.2:无法重现,4:以后解决,5:需求要求,5.1:设计要求,6:解决中,7:关闭(已验证解决),7.1:暂时关闭",'defaultdata'=>"1",'visibleWhenAdd'=>"false",),
 array('id'=>"sort",'name'=>"类别",'fieldtype'=>"int",'type'=>"dropdown",'data'=>"1:bug,2:改进,3:新功能",'isvisible'=>"false",'forsearch'=>"true",'nullable'=>"false",),
 array('id'=>"SYS_ORGID",'name'=>"组织ID",'fieldtype'=>"int",'type'=>"SYS_ORGID",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"SYS_ADDUSER",'name'=>"创建者",'fieldtype'=>"string",'type'=>"SYS_ADDUSER",'visibleWhenAdd'=>"false",'readonly'=>"true",'forsearch'=>"true",),
 array('id'=>"SYS_ADDTIME",'name'=>"创建时间",'fieldtype'=>"datetime",'type'=>"SYS_ADDTIME",'visibleWhenAdd'=>"false",'readonly'=>"true",'forsearch'=>"true",),
 array('id'=>"SYS_EDITUSER",'name'=>"更新人",'fieldtype'=>"string",'type'=>"SYS_EDITUSER",'data'=>"sql:select a.name,b.name as staffusername   from sys_user a left join sys_staff b on   b.username=a.name where a.orgids like   '%orgid()%' order by staffusername",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"SYS_EDITTIME",'name'=>"更新时间",'fieldtype'=>"datetime",'type'=>"SYS_EDITTIME",'visibleWhenAdd'=>"false",'readonly'=>"true",),
),

) ?>