<?php return array(
'id'=>"oa_project_task_bytype",
'title'=>"任务列表-按项目分组",
'base'=>"oa_project_task",
'sql'=>"select a.*,(select name from oa_project where id=a.projectid) as projectname from oa_task a",
'orderby'=>"projectname desc",
'groupby'=>"y",
'wayofcopyfields'=>"onlycopyprop",
'fields'=>array(
 array('id'=>"id",'name'=>"ID",'fieldtype'=>"int",),
 array('id'=>"projectid",'name'=>"项目",),
 array('id'=>"name",'name'=>"任务名称",),
 array('id'=>"tasktype",'name'=>"工作类别",),
 array('id'=>"begindate",'name'=>"开始日期",),
 array('id'=>"enddate",'name'=>"结束日期",),
 array('id'=>"executer",'name'=>"执行人",),
 array('id'=>"executerid",'name'=>"执行人",),
 array('id'=>"SYS_ADDUSER",'name'=>"下达人",),
 array('id'=>"worktime",'name'=>"工时",),
 array('id'=>"status",'name'=>"状态",),
 array('id'=>"finishper",'name'=>"完成率",),
 array('id'=>"detail",'name'=>"任务描述",),
 array('id'=>"notes",'name'=>"备注",),
 array('id'=>"SYS_ADDTIME",'name'=>"创建时间",),
 array('id'=>"SYS_EDITTIME",'name'=>"更新时间",),
 array('id'=>"SYS_EDITUSER",'name'=>"更新人",),
 array('id'=>"SYS_ORGID",'name'=>"组织ID",),
 array('id'=>"projectname",'name'=>"项目名称",'virtualfield'=>"true",),
),

) ?>