<?php return array(
'id'=>"oa_project_newtask",
'title'=>"我的新任务",
'base'=>"oa_project_task",
'editurl'=>"default",
'filter'=>"status='plan' and executerid = Me() ",
'actions'=>"open,search,page",
'wayofcopyfields'=>"parent_and_child",
'fields'=>array(
 array('id'=>"id",'name'=>"ID",'readonly'=>"true",),
 array('id'=>"projectid",'name'=>"项目",'isvisible'=>"true",'visibleWhenAdd'=>"true",'readonly'=>"true",),
 array('id'=>"tasktype",'name'=>"工作类别",'readonly'=>"true",),
 array('id'=>"name",'name'=>"任务名称",'readonly'=>"true",),
 array('id'=>"worktime",'name'=>"工时",'readonly'=>"true",),
 array('id'=>"begindate",'name'=>"开始日期",'readonly'=>"true",),
 array('id'=>"enddate",'name'=>"结束日期",'readonly'=>"true",),
 array('id'=>"executerid",'name'=>"执行人",'readonly'=>"true",),
 array('id'=>"status",'name'=>"状态",'type'=>"dropdown",'data'=>"plan:计划,doing:执行,done:完成,better:优化,checked:验收,cancel:取消",),
 array('id'=>"executer",'name'=>"执行人",'readonly'=>"true",),
 array('id'=>"price",'name'=>"单价",'readonly'=>"true",),
 array('id'=>"totalprice",'name'=>"总价",'readonly'=>"true",),
 array('id'=>"detail",'name'=>"任务描述",'readonly'=>"true",),
 array('id'=>"attach",'name'=>"附件",'readonly'=>"true",),
 array('id'=>"cat",'name'=>"任务记录类别",'readonly'=>"true",),
 array('id'=>"SYS_EDITTIME",'name'=>"更新时间",'readonly'=>"true",),
 array('id'=>"SYS_ORGID",'name'=>"组织ID",),
 array('id'=>"SYS_ADDUSER",'name'=>"创建人",),
 array('id'=>"SYS_ADDTIME",'name'=>"创建时间",),
 array('id'=>"SYS_EDITUSER",'name'=>"更新人",),
),

) ?>