<?php return array(
'id'=>"oa_pm_inputprojectcost_my",
'title'=>"我的项目成本管理",
'base'=>"oa_pm_inputprojectcost",
'editurl'=>"oa/Project/inputProjectCost",
'addurl'=>"oa/Project/inputProjectCost",
'filter'=>"SYS_ADDUSER=loginuser()",
'orderby'=>"period desc",
'groupby'=>"y",
'wayofcopyfields'=>"parent_and_child",
'fields'=>array(
 array('id'=>"sortindex",'name'=>"序号",),
 array('id'=>"id",'name'=>"ID",),
 array('id'=>"staffid",'name'=>"执行人",),
 array('id'=>"period",'name'=>"周期",'readonly'=>"true",),
 array('id'=>"startdate",'name'=>"开始日期",'readonly'=>"true",),
 array('id'=>"enddate",'name'=>"结束日期",'readonly'=>"true",),
 array('id'=>"projectid",'name'=>"项目",),
 array('id'=>"hour_notconfirmed",'name'=>"填报工时",),
 array('id'=>"hours",'name'=>"有效工时",'readonly'=>"true",),
 array('id'=>"status",'name'=>"状态",'readonly'=>"true",),
 array('id'=>"notes",'name'=>"备注",'readonly'=>"true",),
 array('id'=>"SYS_ADDUSER",'name'=>"创建者",),
 array('id'=>"SYS_ADDTIME",'name'=>"创建时间",),
 array('id'=>"SYS_EDITUSER",'name'=>"更新者",),
 array('id'=>"SYS_EDITTIME",'name'=>"更新时间",),
 array('id'=>"SYS_ORGID",'name'=>"组织ID",),
),

) ?>