<?php return array(
'id'=>"oa_project_basic",
'title'=>"项目基本信息",
'tablename'=>"oa_project",
'actions'=>"add,edit,",
'wayofcopyfields'=>"onlycopyprop",
'cols'=>"1",
'sql_after_deleted'=>"delete from oa_task where projectid=recordid()",
'more'=>"[PUBLIC]",
'fields'=>array(
 array('id'=>"id",'name'=>"ID",'fieldtype'=>"int",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"name",'name'=>"项目名称",'forsearch'=>"true",'nullable'=>"false",),
 array('id'=>"begindate",'name'=>"开始日期",'fieldtype'=>"date",'type'=>"date",'defaultdata'=>"today()",),
 array('id'=>"enddate",'name'=>"结束日期",'fieldtype'=>"date",'type'=>"date",),
 array('id'=>"executer",'name'=>"负责人",'forsearch'=>"true",),
 array('id'=>"status",'name'=>"状态",'fieldtype'=>"string",'length'=>"10",'type'=>"dropdown",'data'=>",plan:计划,doing:执行,done:完成,cancel:取消",'defaultdata'=>"plan",'forsearch'=>"true",),
 array('id'=>"tasktypes",'name'=>"任务分类设置",'type'=>"popupselectone",'data'=>"model:oa_tasktype",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"content",'name'=>"项目概述",'type'=>"textarea",'width'=>"450px",'height'=>"200px",),
 array('id'=>"tag",'name'=>"标记",'fieldtype'=>"string",'length'=>"50",'type'=>"checkboxlist",'data'=>"star:常用,public:公开",),
 array('id'=>"taskfields",'name'=>"任务字段",'type'=>"checkboxlist",'data'=>"name:任务名称,begindate:开始,enddate:结束,executer:执行人,finishper:状态,worktime:工时,priority:优先级,score:评分,notes:备注,price:单价,totalprice:总价,unitname:单位,amount:任务量,SYS_ADDTIME:创建时间",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"diyfields",'name'=>"自定义字段",'defaultdata'=>"字段1,字段2,字段3,字段4,字段5",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"show_options",'name'=>"甘特图显示选项",'fieldtype'=>"string",'length'=>"50",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"language",'name'=>"语言",'fieldtype'=>"string",'length'=>"2",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"SYS_ADDUSER",'name'=>"创建者",'fieldtype'=>"string",'length'=>"50",'type'=>"SYS_ADDUSER",'isvisible'=>"false",'visibleWhenAdd'=>"false",'readonly'=>"true",'forsearch'=>"true",),
 array('id'=>"SYS_ADDTIME",'name'=>"创建日期",'fieldtype'=>"date",'type'=>"date",'defaultdata'=>"today()",'visibleWhenAdd'=>"false",'readonly'=>"true",'forsearch'=>"true",'style'=>"text-align:center",),
 array('id'=>"SYS_EDITUSER",'name'=>"更新人",'fieldtype'=>"string",'length'=>"50",'type'=>"SYS_EDITUSER",'isvisible'=>"false",'visibleWhenAdd'=>"false",'readonly'=>"true",),
 array('id'=>"SYS_EDITTIME",'name'=>"更新时间",'fieldtype'=>"datetime",'type'=>"SYS_EDITTIME",'isvisible'=>"false",'visibleWhenAdd'=>"false",'readonly'=>"true",),
),

) ?>