<?php return array(
'id'=>"sys_function",
'title'=>"功能菜单列表",
'tablename'=>"sys_function",
'orderby'=>"groupno,sort",
'pagerows'=>"10",
'actions'=>"all",
'fields'=>array(
 array('id'=>"id",'name'=>"ID",'isvisible'=>"false",'visibleWhenAdd'=>"false",'readonly'=>"true",),
 array('id'=>"name",'name'=>"名称",'forsearch'=>"true",'nullable'=>"false",),
 array('id'=>"no",'name'=>"编码",'unique'=>"true",'forsearch'=>"true",'nullable'=>"false",),
 array('id'=>"groupno",'name'=>"上级菜单",'forsearch'=>"true",),
 array('id'=>"type",'name'=>"类别",'fieldtype'=>"string",'type'=>"dropdown",'data'=>":,form:表单,table:表格,url:网址,html:HTML",),
 array('id'=>"modelid",'name'=>"模型",'fieldtype'=>"string",),
 array('id'=>"url",'name'=>"url",'type'=>"textarea",'isvisible'=>"false",'forsearch'=>"true",),
 array('id'=>"content",'name'=>"HTML内容",'fieldtype'=>"string",'length'=>"8000",'type'=>"richeditor",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"apps",'name'=>"所属组织",'type'=>"checkboxlist",'data'=>"sql:select code,name from sys_org",'forsearch'=>"true",),
 array('id'=>"models",'name'=>"模型ID",'fieldtype'=>"string",'isvisible'=>"false",),
 array('id'=>"status",'name'=>"状态",'type'=>"radio",'data'=>"visible:显示,:隐藏",'defaultdata'=>"visible",'forsearch'=>"true",),
 array('id'=>"notes",'name'=>"备注",'fieldtype'=>"string",'isvisible'=>"false",),
 array('id'=>"sort",'name'=>"排序",'fieldtype'=>"float",'isvisible'=>"false",),
 array('id'=>"groupname",'name'=>"所属功能分组",'fieldtype'=>"string",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
),

) ?>