<?php return array(
'id'=>"list_product",
'title'=>"产品列表",
'notes'=>"CRM/Product/editoneproduct",
'tablename'=>"crm_product",
'openurl'=>"default",
'orderby'=>"type,orderindex",
'pagerows'=>"10",
'actions'=>"add,del,edit,search,page",
'fields'=>array(
 array('id'=>"id",'name'=>"ID",'fieldtype'=>"int",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
 array('id'=>"no",'name'=>"编号",'isvisible'=>"false",'visibleWhenAdd'=>"false",'forsearch'=>"true",'style'=>"text-align:center",),
 array('id'=>"name",'name'=>"名称",'forsearch'=>"true",'nullable'=>"false",'style'=>"text-align:center",),
 array('id'=>"unit",'name'=>"单位",'forsearch'=>"true",'nullable'=>"true",'style'=>"text-align:center",),
 array('id'=>"price",'name'=>"单价",'fieldtype'=>"float",'forsearch'=>"true",),
 array('id'=>"type",'name'=>"大类",'type'=>"dropdown",'data'=>"sql:select distinct(type) from crm_product",'forsearch'=>"true",),
 array('id'=>"yongtu",'name'=>"小类",'forsearch'=>"true",'style'=>"text-align:center",),
 array('id'=>"orderindex",'name'=>"排序",'fieldtype'=>"float",'forsearch'=>"true",'style'=>"text-align:center",),
 array('id'=>"modules",'name'=>"包含模块",'fieldtype'=>"string",'type'=>"textarea",),
 array('id'=>"detail",'name'=>"内容",'type'=>"textarea",'forsearch'=>"true",),
 array('id'=>"notes",'name'=>"备注",'type'=>"textarea",'forsearch'=>"true",),
 array('id'=>"isup",'name'=>"不升级",'type'=>"checkbox",'isvisible'=>"false",),
 array('id'=>"upgradeprice081",'name'=>"08版升级费",'fieldtype'=>"int",'isvisible'=>"false",),
 array('id'=>"upgradeprice05",'name'=>"05版升级费",'fieldtype'=>"int",'isvisible'=>"false",),
 array('id'=>"upgradeprice02",'name'=>"02版升级费",'fieldtype'=>"int",'isvisible'=>"false",),
 array('id'=>"upgradeprice98",'name'=>"98版升级费",'fieldtype'=>"int",'isvisible'=>"false",),
),

) ?>