<?php return array(
'id'=>"list_customer_agent",
'title'=>"我的客户列表",
'tablename'=>"crm_customer",
'filter'=>"agent in (select no from crm_agent where username = loginuser())",
'open_window_style'=>"popup:middle",
'pagerows'=>"10",
'actions'=>"search,page",
'cols'=>"2",
'fields'=>array(
 array('id'=>"id",'name'=>"ID",'isvisible'=>"false",'visibleWhenAdd'=>"false",'width'=>"250px",),
 array('id'=>"no",'name'=>"用户号",'unique'=>"true",'forsearch'=>"true",'nullable'=>"false",'style'=>"text-align:center",'width'=>"250px",),
 array('id'=>"name",'name'=>"单位名称",'forsearch'=>"true",'nullable'=>"false",'width'=>"250px",),
 array('id'=>"address",'name'=>"地址",'forsearch'=>"true",'nullable'=>"false",'width'=>"250px",),
 array('id'=>"contacts",'name'=>"联系人",'forsearch'=>"true",'nullable'=>"false",'style'=>"text-align:center",'width'=>"250px",),
 array('id'=>"agent",'name'=>"销售机构",'forsearch'=>"true",'nullable'=>"false",'style'=>"text-align:center",'width'=>"250px",),
 array('id'=>"district",'name'=>"所属区域",'forsearch'=>"true",'style'=>"text-align:center",'width'=>"250px",),
 array('id'=>"biaoji",'name'=>"标记",'defaultdata'=>"未审核",'isvisible'=>"false",'visibleWhenAdd'=>"false",'forsearch'=>"true",'width'=>"200px",),
 array('id'=>"post",'name'=>"邮编",'length'=>"6",'isvisible'=>"false",'visibleWhenAdd'=>"false",'forsearch'=>"true",'nullable'=>"false",'width'=>"200px",),
 array('id'=>"tel",'name'=>"电话",'isvisible'=>"false",'visibleWhenAdd'=>"false",'forsearch'=>"true",'nullable'=>"false",'width'=>"200px",),
 array('id'=>"phone",'name'=>"手机",'isvisible'=>"false",'visibleWhenAdd'=>"false",'forsearch'=>"true",'nullable'=>"true",'width'=>"200px",),
 array('id'=>"fax",'name'=>"传真",'isvisible'=>"false",'visibleWhenAdd'=>"false",'forsearch'=>"true",'width'=>"200px",),
 array('id'=>"email",'name'=>"邮箱",'isvisible'=>"false",'visibleWhenAdd'=>"false",'forsearch'=>"true",'width'=>"200px",),
 array('id'=>"notes",'name'=>"备注",'isvisible'=>"false",'visibleWhenAdd'=>"false",'forsearch'=>"true",'width'=>"200px",),
 array('id'=>"srctype",'name'=>"来源",'fieldtype'=>"string",'type'=>"dropdown",'data'=>"直销,渠道",'isvisible'=>"false",'visibleWhenAdd'=>"false",'width'=>"200px",),
),

) ?>