<?php return array(
'id'=>"list_customer",
'title'=>"客户列表",
'tablename'=>"crm_customer",
'openurl'=>"CRM/Customer/showonecustomer",
'editurl'=>"CRM/Customer/editcustomer",
'addurl'=>"CRM/Customer/editcustomer",
'groupby'=>"n",
'open_window_style'=>"popup:middle",
'pagerows'=>"20",
'actions'=>"add,del,open,edit,search,search2,page,export",
'cols'=>"2",
'fields'=>array(
 array('id'=>"id",'name'=>"ID",'isvisible'=>"false",'visibleWhenAdd'=>"false",'width'=>"250px",),
 array('id'=>"no",'name'=>"用户号",'forsearch'=>"true",'nullable'=>"false",'style'=>"text-align:center;width:50px;overflow:hidden",'width'=>"250px",),
 array('id'=>"name",'name'=>"单位名称",'forsearch'=>"true",'nullable'=>"false",'style'=>"width:200px;overflow:hidden",'width'=>"250px",),
 array('id'=>"address",'name'=>"地址",'forsearch'=>"true",'nullable'=>"false",'style'=>"width:200px;overflow:hidden",'width'=>"250px",),
 array('id'=>"contacts",'name'=>"联系人",'forsearch'=>"true",'nullable'=>"false",'style'=>"text-align:center;width:90px;overflow:hidden",'width'=>"250px",),
 array('id'=>"agent",'name'=>"销售机构",'forsearch'=>"true",'nullable'=>"false",'style'=>"text-align:center;width:50px;overflow:hidden",'width'=>"250px",),
 array('id'=>"district",'name'=>"所属区域",'isvisible'=>"false",'forsearch'=>"true",'style'=>"text-align:center;width:50px;overflow:hidden",'width'=>"250px",),
 array('id'=>"biaoji",'name'=>"标记",'defaultdata'=>"未审核",'isvisible'=>"false",'visibleWhenAdd'=>"false",'forsearch'=>"true",'style'=>"text-align:center;width:50px;overflow:hidden",'width'=>"200px",),
 array('id'=>"post",'name'=>"邮编",'length'=>"6",'forsearch'=>"true",'nullable'=>"false",'style'=>"text-align:center;width:50px;overflow:hidden",'width'=>"200px",'formate'=>"post",),
 array('id'=>"tel",'name'=>"电话",'forsearch'=>"true",'nullable'=>"false",'style'=>";width:90px;overflow:hidden",'width'=>"200px",'formate'=>"tel",),
 array('id'=>"phone",'name'=>"手机",'forsearch'=>"true",'nullable'=>"true",'style'=>"text-align:center;width:50px;overflow:hidden",'width'=>"200px",),
 array('id'=>"fax",'name'=>"传真",'forsearch'=>"true",'style'=>";width:50px;overflow:hidden",'width'=>"200px",),
 array('id'=>"email",'name'=>"邮箱",'forsearch'=>"true",'style'=>"text-align:center;width:50px;overflow:hidden",'width'=>"200px",),
 array('id'=>"notes",'name'=>"备注",'forsearch'=>"true",'style'=>";width:90px;overflow:hidden",'width'=>"200px",),
 array('id'=>"srctype",'name'=>"来源",'fieldtype'=>"string",'type'=>"dropdown",'data'=>"直销,渠道,分部",'visibleWhenAdd'=>"false",'style'=>"text-align:center;width:50px;overflow:hidden",'width'=>"200px",),
 array('id'=>"owner",'name'=>"输入者",'fieldtype'=>"string",'type'=>"SYS_ADDUSER",'isvisible'=>"false",'visibleWhenAdd'=>"false",),
),

) ?>