<?php return array(
'id'=>"list_topic",
'title'=>"知识列表",
'tablename'=>"oa_topic",
'openurl'=>"default",
'editurl'=>"default",
'addurl'=>"default",
'delurl'=>"default",
'orderby'=>"id desc",
'open_window_style'=>"samewindow",
'pagerows'=>"10",
'actions'=>"add,del,edit,search,search2,filter,filter2,page,export",
'keyfield'=>"id",
'fields'=>array(
 array('id'=>"id",'name'=>"ID",'fieldtype'=>"int",'isvisible'=>"true",'visibleWhenAdd'=>"false",'readonly'=>"true",'forsearch'=>"true",),
 array('id'=>"name",'name'=>"标题",'length'=>"100",'defaultdata'=>"新标题1",'readonly'=>"true",'forsearch'=>"true",),
 array('id'=>"content",'name'=>"附件",'type'=>"richeditor",'defaultdata'=>"1234",'isvisible'=>"false",'forsearch'=>"true",),
 array('id'=>"type",'name'=>"类别",'type'=>"dropdown",'data'=>":,1:技术,2:美工",'defaultdata'=>"技术",'readonly'=>"true",),
 array('id'=>"vip",'name'=>"非常重要",'defaultdata'=>"true",'forsearch'=>"true",),
 array('id'=>"gender",'name'=>"性别",'type'=>"radio",'data'=>"1:男,2:女",'defaultdata'=>"男",'forsearch'=>"true",),
 array('id'=>"float1",'name'=>"小数",'forsearch'=>"true",'formate'=>"float",),
 array('id'=>"related",'name'=>"相关领域",'type'=>"image",'data'=>"1:IT,2:社会,3:国际",'forsearch'=>"true",),
 array('id'=>"loginuser",'name'=>"创建者",'defaultdata'=>"loginuser()",'forsearch'=>"true",),
 array('id'=>"addtime",'name'=>"创建时间",'type'=>"date",'defaultdata'=>"now()",'forsearch'=>"true",),
 array('id'=>"f12",'name'=>"新字段",),
 array('id'=>"staffid",'name'=>"姓名",'type'=>"dropdown",'data'=>"sql:select id,name from sys_staff",'forsearch'=>"true",),
),

) ?>